# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: local  # Using the "local" agent pool
  demands: Agent.Version -gtVersion 2.163.1

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '263f5270-28e6-44b9-bb36-95e4039fdb72'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/achyutmallareddy/My-Azure-Projects/main/ARMPipeline-repo/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName armdemo'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'